/* ============================================================
   Nails by Kotomi — Bilingual Content
   To update text: edit here. Both languages update together.
   Keys used by data-i18n / data-i18n-html / data-i18n-label
   ============================================================ */

var CONTENT = {

  /* ══════════════════════════════════════════════════════════
     ENGLISH
  ══════════════════════════════════════════════════════════ */
  en: {

    /* ── Shared: Navigation ── */
    nav: {
      home:           'Home',
      gallery:        'Gallery',
      services:       'Services',
      bookNow:        'Book Now',
      mobileServices: 'Services & Pricing',
      mobileBook:     'Book an Appointment',
      langLabel:      'Switch to Japanese',
    },

    /* ── Shared: Footer ── */
    footer: {
      tagline:      'Professional nail artistry in a private, welcoming studio. Every client, every set, every time.',
      navigate:     'Navigate',
      home:         'Home',
      gallery:      'Gallery',
      servicesLink: 'Services & Pricing',
      bookLink:     'Book an Appointment',
      contact:      'Get in Touch',
      hours:        'Mon–Sat: 10:00 – 18:00<br>Sunday: By request',
      copyright:    'Nails by Kotomi. All rights reserved.',
    },

    /* ── Home page ── */
    home: {
      heroEyebrow:  'Professional Nail Technician · London',
      heroTitle:    'Where Beauty<br />Meets Precision',
      heroP:        'Bespoke nail artistry crafted with care — from classic elegance to expressive nail art.',
      bookBtn:      'Book an Appointment',
      viewServices: 'View Services',
      scroll:       'Scroll',

      galleryEyebrow: 'Portfolio',
      galleryTitle:   'A Glimpse of the Work',
      galleryP:       'Every set is a one-of-a-kind creation. Browse a selection of recent looks below.',
      gItem0: 'Gel Manicure',
      gItem1: 'Nail Art',
      gItem2: 'Acrylic Set',
      gItem3: 'Ombre Design',
      gItem4: 'French Tips',
      gItem5: 'Pedicure',
      viewGallery: 'View Full Gallery',

      aboutEyebrow: 'About Kotomi',
      aboutTitle:   'Passion for the Perfect Finish',
      aboutP1: "Hi, I'm Kotomi — a fully qualified nail technician with a deep love for precision, artistry, and making clients feel genuinely cared for. Every appointment is a personalised experience tailored to you.",
      aboutP2: "Whether you're after a sleek, understated gel manicure or an intricate hand-painted design, I bring the same level of dedication to every single set of nails.",
      aboutP3: "I work from my cosy private studio, so you can expect a relaxed, one-on-one experience from start to finish.",
      statClients:   'Happy Clients',
      statRating:    'Average Rating',
      statYears:     'Years Experience',
      bookWithMe:    'Book with Me',

      testimonialsEyebrow: 'Client Love',
      testimonialsTitle:   'What Clients Are Saying',
      testimonialsP:       "Don't just take my word for it — here's what some lovely clients have shared.",
      t1quote:  '"Kotomi is genuinely the most talented nail tech I\'ve ever visited. My gel set lasted over four weeks without a single chip — absolutely obsessed."',
      t1author: '— Sarah M., London',
      t2quote:  '"I came in with a vague idea and left with the most gorgeous nail art I\'ve ever had. Kotomi listened so carefully and brought my vision to life perfectly."',
      t2author: '— Priya K., London',
      t3quote:  '"The studio atmosphere is so calming and Kotomi makes every appointment feel like a treat. My acrylic set looked flawless for weeks. I won\'t go anywhere else."',
      t3author: '— Jessica L., London',

      ctaEyebrow: 'Ready to treat yourself?',
      ctaTitle:   'Book Your Next Appointment',
      ctaP:       "Slots go quickly — secure yours today and let's create something beautiful together.",
      ctaBtn:     'Book Now',
    },

    /* ── Services page ── */
    services: {
      heroEyebrow: "What's on Offer",
      heroTitle:   'Services & Pricing',
      heroP:       'Transparent pricing, no hidden costs — just beautiful nails every time.',

      menuEyebrow: 'Menu',
      menuTitle:   'Core Services',
      menuP:       'All appointments include a consultation, cuticle care, shape & finish.',

      gel: {
        name:  'Gel Manicure',
        price: '£45',
        unit:  '/ session',
        desc:  'A long-lasting, high-shine gel finish that keeps your nails looking freshly done for up to four weeks. Perfect for everyday wear.',
        i1: 'Nail shape & cuticle prep',
        i2: 'Base, colour & top coat gel',
        i3: 'LED cure & nourishing oil finish',
        i4: 'Lasts 3–4 weeks',
        btn: 'Book This Service',
      },
      acrylic: {
        name:  'Acrylic Full Set',
        price: '£55',
        unit:  '/ session',
        desc:  'Build strength and length with a classic acrylic full set. Available in a range of shapes — square, coffin, almond, stiletto, and more.',
        i1: 'Natural nail prep & tip application',
        i2: 'Acrylic sculpt in your chosen shape',
        i3: 'Gel colour or classic polish finish',
        i4: 'Filing, buffing & cuticle oil',
        btn: 'Book This Service',
      },
      art: {
        name:  'Nail Art',
        price: 'from £10',
        unit:  '/ add-on',
        desc:  "From delicate hand-painted florals to bold geometric designs — nail art is added on top of any service. Bring your inspo and we'll make it happen.",
        i1: 'Freehand painting & fine detail work',
        i2: 'Stamping, foils & chrome effects',
        i3: '3D embellishments & gems',
        i4: 'Price varies by complexity',
        btn: 'Book This Service',
      },
      pedicure: {
        name:  'Pedicure',
        price: '£40',
        unit:  '/ session',
        desc:  'A relaxing, thorough pedicure that leaves your feet feeling soft and your toes perfectly polished. Ideal as a standalone treat or paired with a manicure.',
        i1: 'Soak, exfoliation & heel treatment',
        i2: 'Cuticle care & nail shaping',
        i3: 'Gel or classic polish finish',
        i4: 'Hydrating foot massage',
        btn: 'Book This Service',
      },

      addonsEyebrow: 'Extras',
      addonsTitle:   'Add-Ons & Enhancements',
      addonsP:       'Elevate any service with one of these popular extras.',
      addon1name: 'Gel Removal',    addon1price: '£10',
      addon2name: 'Acrylic Infill', addon2price: '£35',
      addon3name: 'Chrome Powder',  addon3price: '£8',
      addon4name: 'Nail Gems',      addon4price: 'from £5',
      addon5name: 'Gold Foil',      addon5price: '£6',
      addon6name: 'Paraffin Wax',   addon6price: '£12',
      addon7name: 'Nail Repair',    addon7price: '£5 / nail',
      addon8name: 'French Tip',     addon8price: '£8',

      policiesEyebrow: 'Good to Know',
      policiesTitle:   'Booking & Policies',
      cancelTitle: 'Cancellations',
      cancelP:     "Please give at least 24 hours' notice to cancel or reschedule. Late cancellations may incur a 50% fee.",
      paymentTitle: 'Payment',
      paymentP:     'Card, bank transfer and cash accepted. A deposit may be required for first-time bookings and longer appointments.',
      lateTitle: 'Late Arrivals',
      lateP:     "Please arrive on time. If you're more than 15 minutes late I may need to shorten or reschedule your appointment.",

      ctaEyebrow: 'Ready?',
      ctaTitle:   'Secure Your Slot Today',
      ctaP:       'Availability moves quickly — book online in under a minute.',
      ctaBtn:     'Book an Appointment',
    },

    /* ── Gallery page ── */
    gallery: {
      heroEyebrow: 'Portfolio',
      heroTitle:   'The Gallery',
      heroP:       'A curated collection of nail looks — from everyday elegance to statement artistry.',

      filterAll:      'All',
      filterGel:      'Gel',
      filterAcrylic:  'Acrylic',
      filterArt:      'Nail Art',
      filterPedicure: 'Pedicures',

      i0t: 'Gel · Soft Blush',          i0l: 'Gel Manicure — Soft Blush',
      i1t: 'Nail Art · Floral',          i1l: 'Nail Art — Floral Impressions',
      i2t: 'Acrylic · Nude Square',      i2l: 'Acrylic Full Set — Nude Square',
      i3t: 'Pedicure · Classic Red',     i3l: 'Pedicure — Classic Red',
      i4t: 'Gel · Milky White',          i4l: 'Gel Manicure — Milky White',
      i5t: 'Nail Art · Marble',          i5l: 'Nail Art — Abstract Marble',
      i6t: 'Acrylic · Ombre',            i6l: 'Acrylic — Ombre Pink to White',
      i7t: 'Gel · Deep Berry',           i7l: 'Gel Manicure — Deep Berry',
      i8t: 'Pedicure · Nude & Gold',     i8l: 'Pedicure — Nude & Gold Foil',
      i9t: 'Nail Art · Botanical',       i9l: 'Nail Art — Botanical Line Work',
      i10t: 'Acrylic · Clear Coffin',    i10l: 'Acrylic — Clear Coffin',
      i11t: 'Gel · French Tips',         i11l: 'Gel Manicure — French Tips',

      empty:    'No images in this category yet — check back soon!',
      ctaEyebrow: 'Love what you see?',
      ctaTitle:   "Let's Create Your Perfect Set",
      ctaP:       "Each look is fully bespoke — bring your inspo pics and we'll make it happen.",
      ctaBtn:     'Book an Appointment',
    },

    /* ── Booking page ── */
    booking: {
      heroEyebrow: 'Online Booking',
      heroTitle:   'Book Your Appointment',
      heroP:       'Choose a service, pick a time, and leave the rest to me.',

      sectionEyebrow: "Let's get you booked in",
      sectionTitle:   'Reserve Your Slot',
      sectionP:       'I\'d love to have you in the studio! Use the calendar below to find a time that works for you. If you have any questions before booking, feel free to reach out at <a href="mailto:hello@nailsbykotomi.com" style="color:var(--pink);text-decoration:underline;text-underline-offset:3px;">hello@nailsbykotomi.com</a>.',

      expectEyebrow: 'Your Visit',
      expectTitle:   'What to Expect',
      expectP:       'A warm, relaxed experience from the moment you walk through the door.',
      step1title: 'Consultation',
      step1p:     "We'll chat about your nail goals, inspo and any concerns before we start.",
      step2title: 'Nail Prep',
      step2p:     'Thorough cuticle care, shaping and surface prep for the best possible finish.',
      step3title: 'Application',
      step3p:     'Precision application of your chosen service, colour and any nail art extras.',
      step4title: 'Finish & Glow',
      step4p:     "Nourishing oil, final inspection, and you're ready to show off your new set.",

      faqEyebrow: 'Questions',
      faqTitle:   'Frequently Asked',
      faq1q: 'How long does a gel manicure take?',
      faq1a: 'A standard gel manicure takes approximately 60–75 minutes, including nail prep, colour application and LED curing. Adding nail art may extend the appointment.',
      faq2q: 'Do I need to do anything before my appointment?',
      faq2a: "Please arrive with clean nails — remove any existing polish or gel at home if possible. Avoid applying hand cream on the day, as it can affect adhesion. That's all!",
      faq3q: 'Can I bring my own nail colour?',
      faq3a: "Yes! You're welcome to bring your own gel or regular polish. Please let me know in advance so I can check compatibility with the products I use.",
      faq4q: 'What if I need to cancel or reschedule?',
      faq4a: "No problem — life happens! Please give at least 24 hours' notice via the booking system or by email. Cancellations with less than 24 hours' notice may incur a 50% charge.",
    },
  },

  /* ══════════════════════════════════════════════════════════
     JAPANESE
  ══════════════════════════════════════════════════════════ */
  ja: {

    nav: {
      home:           'ホーム',
      gallery:        'ギャラリー',
      services:       'メニュー',
      bookNow:        'ご予約',
      mobileServices: 'メニューと料金',
      mobileBook:     'ご予約',
      langLabel:      'Switch to English',
    },

    footer: {
      tagline:      'プライベートスタジオで提供する、丁寧なネイルアート。すべてのお客様に、最高の仕上がりを。',
      navigate:     'ナビゲート',
      home:         'ホーム',
      gallery:      'ギャラリー',
      servicesLink: 'メニューと料金',
      bookLink:     'ご予約',
      contact:      'お問い合わせ',
      hours:        '月〜土：10:00〜18:00<br>日曜：応相談',
      copyright:    'Nails by Kotomi. 全著作権所有。',
    },

    home: {
      heroEyebrow:  'プロネイルテクニシャン・ロンドン',
      heroTitle:    '美しさと<br />繊細さの融合',
      heroP:        '丁寧に仕上げるオーダーメイドのネイルアート。クラシックな上品さから、個性的なデザインまで。',
      bookBtn:      'ご予約',
      viewServices: 'メニューを見る',
      scroll:       'スクロール',

      galleryEyebrow: 'ポートフォリオ',
      galleryTitle:   '作品の一例',
      galleryP:       'すべてのネイルは一点もの。最近の施術例をご覧ください。',
      gItem0: 'ジェルマニキュア',
      gItem1: 'ネイルアート',
      gItem2: 'アクリルセット',
      gItem3: 'オンブレデザイン',
      gItem4: 'フレンチティップス',
      gItem5: 'ペディキュア',
      viewGallery: 'ギャラリーを見る',

      aboutEyebrow: 'コトミについて',
      aboutTitle:   '完璧な仕上がりへの情熱',
      aboutP1: 'こんにちは、コトミです。資格を持つプロのネイルテクニシャンとして、繊細さ・芸術性・そしてお客様への真摯なケアを大切にしています。すべてのご予約は、あなただけのパーソナルな体験をご提供します。',
      aboutP2: 'シンプルなジェルマニキュアから、手の込んだハンドペイントデザインまで、すべての施術に同じ情熱と丁寧さを注いでいます。',
      aboutP3: 'アットホームなプライベートスタジオで、完全マンツーマンの施術をご提供しています。',
      statClients:   'ご満足のお客様',
      statRating:    '平均評価',
      statYears:     '年の経験',
      bookWithMe:    '予約する',

      testimonialsEyebrow: 'お客様の声',
      testimonialsTitle:   'クライアントの声',
      testimonialsP:       '実際にご来店いただいたお客様からの声をご紹介します。',
      t1quote:  '「コトミさんは本当に才能のあるネイリストです。ジェルネイルが4週間以上チップなしで続きました。大満足です。」',
      t1author: '— Sarah M.、ロンドン',
      t2quote:  '「なんとなくのイメージで行ったのに、これまでで一番素敵なネイルアートに仕上げてもらいました。コトミさんはしっかり話を聞いてくれて、完璧に実現してくれました。」',
      t2author: '— Priya K.、ロンドン',
      t3quote:  '「スタジオの雰囲気がとても落ち着いていて、コトミさんの施術は毎回特別な体験です。アクリルネイルも何週間も美しいままでした。もう他には行けません。」',
      t3author: '— Jessica L.、ロンドン',

      ctaEyebrow: 'ご自分へのご褒美に',
      ctaTitle:   '次のご予約を',
      ctaP:       '空きはすぐに埋まります。今日中にご予約を確保して、一緒に美しいネイルを作りましょう。',
      ctaBtn:     '今すぐ予約',
    },

    services: {
      heroEyebrow: 'メニュー',
      heroTitle:   'メニューと料金',
      heroP:       '明瞭な料金体系、隠れた費用はありません。毎回、美しいネイルをお届けします。',

      menuEyebrow: 'メニュー',
      menuTitle:   '主なサービス',
      menuP:       'すべての施術にカウンセリング、甘皮ケア、シェイプ、仕上げが含まれます。',

      gel: {
        name:  'ジェルマニキュア',
        price: '£45',
        unit:  '/ 施術',
        desc:  '最長4週間続く、高光沢のジェル仕上げ。毎日のウェアに最適です。',
        i1: 'シェイプ・甘皮ケア',
        i2: 'ベース・カラー・トップコートジェル',
        i3: 'LEDキュア・保湿オイル仕上げ',
        i4: '3〜4週間持続',
        btn: 'このサービスを予約',
      },
      acrylic: {
        name:  'アクリルフルセット',
        price: '£55',
        unit:  '/ 施術',
        desc:  '強度と長さを出すクラシックなアクリルフルセット。スクエア、コフィン、アーモンド、スティレットなど様々な形からお選びいただけます。',
        i1: '自爪ケア・チップ装着',
        i2: 'お好みの形にアクリルスカルプ',
        i3: 'ジェルカラーまたは通常ポリッシュ仕上げ',
        i4: 'ファイリング、バッフィング、キューティクルオイル',
        btn: 'このサービスを予約',
      },
      art: {
        name:  'ネイルアート',
        price: '£10〜',
        unit:  '/ 追加',
        desc:  '繊細なハンドペイントのフローラルから、大胆なジオメトリックデザインまで。どのサービスにも追加できます。インスピレーション画像をお持ちください。',
        i1: 'フリーハンドペイント・精密ディテール',
        i2: 'スタンピング、フォイル、クロームエフェクト',
        i3: '3Dエンベリッシュメント・ジェム',
        i4: '複雑さによって料金が異なります',
        btn: 'このサービスを予約',
      },
      pedicure: {
        name:  'ペディキュア',
        price: '£40',
        unit:  '/ 施術',
        desc:  'リラックスできる丁寧なペディキュア。足元を美しく整えます。単独でも、マニキュアとのセットでもお楽しみいただけます。',
        i1: 'ソーク、角質除去、かかとケア',
        i2: '甘皮ケア・シェイプ',
        i3: 'ジェルまたは通常ポリッシュ仕上げ',
        i4: '保湿フットマッサージ',
        btn: 'このサービスを予約',
      },

      addonsEyebrow: '追加メニュー',
      addonsTitle:   '追加メニュー・オプション',
      addonsP:       '人気の追加メニューでさらにグレードアップ。',
      addon1name: 'ジェルオフ',        addon1price: '£10',
      addon2name: 'アクリルインフィル', addon2price: '£35',
      addon3name: 'クロームパウダー',   addon3price: '£8',
      addon4name: 'ネイルジェム',       addon4price: '£5〜',
      addon5name: 'ゴールドフォイル',   addon5price: '£6',
      addon6name: 'パラフィンワックス', addon6price: '£12',
      addon7name: 'ネイルリペア',       addon7price: '£5 / 本',
      addon8name: 'フレンチティップ',   addon8price: '£8',

      policiesEyebrow: 'ご注意',
      policiesTitle:   '予約・ポリシー',
      cancelTitle: 'キャンセルについて',
      cancelP:     'キャンセル・変更は24時間前までにお知らせください。24時間以内のキャンセルは50%のキャンセル料が発生する場合があります。',
      paymentTitle: 'お支払い',
      paymentP:     'カード、銀行振込、現金をご利用いただけます。初回予約や長時間のご予約には、デポジットが必要な場合があります。',
      lateTitle: '遅刻について',
      lateP:     'お時間通りにお越しください。15分以上の遅刻の場合、施術を短縮またはご予約を変更させていただく場合があります。',

      ctaEyebrow: 'ご準備はよろしいですか？',
      ctaTitle:   '今すぐご予約を',
      ctaP:       '空きはすぐに埋まります。オンラインで1分以内にご予約いただけます。',
      ctaBtn:     'ご予約',
    },

    gallery: {
      heroEyebrow: 'ポートフォリオ',
      heroTitle:   'ギャラリー',
      heroP:       '日常のエレガンスから個性的なアートまで、厳選されたネイルコレクション。',

      filterAll:      'すべて',
      filterGel:      'ジェル',
      filterAcrylic:  'アクリル',
      filterArt:      'ネイルアート',
      filterPedicure: 'ペディキュア',

      i0t: 'ジェル · ソフトブラッシュ',      i0l: 'ジェルマニキュア — ソフトブラッシュ',
      i1t: 'ネイルアート · フローラル',        i1l: 'ネイルアート — フローラル',
      i2t: 'アクリル · ヌードスクエア',        i2l: 'アクリルフルセット — ヌードスクエア',
      i3t: 'ペディキュア · クラシックレッド',  i3l: 'ペディキュア — クラシックレッド',
      i4t: 'ジェル · ミルキーホワイト',        i4l: 'ジェルマニキュア — ミルキーホワイト',
      i5t: 'ネイルアート · マーブル',          i5l: 'ネイルアート — マーブル',
      i6t: 'アクリル · オンブレ',              i6l: 'アクリル — オンブレ',
      i7t: 'ジェル · ディープベリー',          i7l: 'ジェルマニキュア — ディープベリー',
      i8t: 'ペディキュア · ヌード & ゴールド', i8l: 'ペディキュア — ヌード & ゴールドフォイル',
      i9t: 'ネイルアート · ボタニカル',        i9l: 'ネイルアート — ボタニカル',
      i10t: 'アクリル · クリアコフィン',       i10l: 'アクリル — クリアコフィン',
      i11t: 'ジェル · フレンチティップス',     i11l: 'ジェルマニキュア — フレンチティップス',

      empty:      'このカテゴリーにはまだ画像がありません。またお越しください！',
      ctaEyebrow: '気に入っていただけましたか？',
      ctaTitle:   'あなただけのネイルを作りましょう',
      ctaP:       'すべてのデザインはオーダーメイド。インスピレーション画像をお持ちいただければ実現します。',
      ctaBtn:     'ご予約',
    },

    booking: {
      heroEyebrow: 'オンライン予約',
      heroTitle:   'ご予約',
      heroP:       'サービスを選んで、お時間を決めて、後はお任せください。',

      sectionEyebrow: 'ご予約を承ります',
      sectionTitle:   'ご予約',
      sectionP:       'スタジオでお待ちしております！下記のカレンダーよりご都合のよいお時間をお選びください。ご不明な点がございましたら、お気軽に <a href="mailto:hello@nailsbykotomi.com" style="color:var(--pink);text-decoration:underline;text-underline-offset:3px;">hello@nailsbykotomi.com</a> までご連絡ください。',

      expectEyebrow: 'ご来店について',
      expectTitle:   'ご来店の流れ',
      expectP:       'ご来店いただいた瞬間から、温かくリラックスできる空間をご提供します。',
      step1title: 'カウンセリング',
      step1p:     'ネイルのご希望、インスピレーション、気になることなどをお伺いします。',
      step2title: 'ネイルケア',
      step2p:     '最高の仕上がりのために、丁寧な甘皮ケア、シェイプ、下準備を行います。',
      step3title: '施術',
      step3p:     'ご希望のサービス、カラー、ネイルアートを丁寧に施術します。',
      step4title: '仕上げ',
      step4p:     '保湿オイル、最終チェック、これで新しいネイルを披露する準備が整いました。',

      faqEyebrow: 'よくあるご質問',
      faqTitle:   'よくあるご質問',
      faq1q: 'ジェルマニキュアはどのくらい時間がかかりますか？',
      faq1a: '通常のジェルマニキュアは、ネイルケア、カラー施術、LEDキュアを含めて約60〜75分です。ネイルアートを追加する場合は時間が延びる場合があります。',
      faq2q: '予約前に準備することはありますか？',
      faq2a: 'できれば、自宅でポリッシュやジェルを落としてきれいな状態でお越しください。当日のハンドクリームは密着に影響するため、塗らずにお越しください。以上です！',
      faq3q: '自分のネイルカラーを持参できますか？',
      faq3a: 'もちろんです！ジェルまたは通常のポリッシュをお持ちいただけます。事前にお知らせいただければ、使用する製品との相性を確認いたします。',
      faq4q: 'キャンセルや変更の場合はどうすればいいですか？',
      faq4a: '予約システムまたはメールにて、24時間前までにご連絡ください。24時間以内のキャンセルには50%のキャンセル料が発生する場合があります。',
    },
  },
};
